### ISSUE TITLE
undefined reference to `WinMain@16'

### ISSUE THREAD

**Issue by TakWolf** [DanqueDynasty/SDL_Demo#1]
I clone this project and have this error.

My environment is：

Windows8.1 
CLion 2016.1
MinGW 3.20

**Comment by TakWolf** [comment]
I use the  SDL2-devel-2.0.4-mingw.

if I use this project or  x86_64-w64-mingw32, then I get a error WinMain@16

if I use i686-w64-mingw32, then I get :

![image](https://cloud.githubusercontent.com/assets/6064962/13985719/406b0c40-f139-11e5-97da-8cfd060e6351.png)

**Comment by TakWolf** [comment]
I have see your essay here:
http://swinginnovations.com/guides-n-how-tos/how-to-configure-sdl-and-clion-on-windows/

so, I should use MinGW-w64 , not MinGW?

**Comment by DanqueDynasty** [comment]
The version of SDL I included in this project is the 64-bit version, built for MinGW x86_64-4.8.3. Seeing as you are using MinGW 3.20, I suspect there may be some legacy issues? Have you downloaded and used the latest headers/libs from SDL?

**Comment by TakWolf** [comment]
Yes, I have download the last version of  SDL2 ( SDL2-2.0.4 ). I have search by google and sdl forum but not found some userful info , it looks that little people write SDL with CLion ( and CMake ?). Most people seems to use visual studio or codeblocks.

I use "visual studio 2015 update 1" with "SDL2-devel-2.0.4-VC.zip"

or "codeblocks C++" with "SDL2-devel-2.0.4-mingw.tar.gz"

or "XCode 7" with "SDL2-2.0.4.dmg", it works well .

But I want change my IDE to CLion...

I am trying MinGW-w64 now...

**Comment by DanqueDynasty** [comment]
When you are linking the project(Line 13 in CMakeList.txt), are you writing SDL2main before SDL? So far most people who encounter the errors you are experiencing have the two flipped.

**Comment by TakWolf** [comment]
target_link_libraries(game SDL2main SDL2)

Yes, it works!  SDL2main should before SDL2!

OH! Sometimes, mistakes always in these Small details.

Thanks very very much!!! Helps a lot!!!

**Comment by DanqueDynasty** [comment]
No problem! Glad I could help :)
